### ISSUE TITLE
部分go程序并不能抓取https

### ISSUE THREAD

**Issue by xiaopihaiK** [Your7Maxx/FlowGod#7]
部分go程序并不能抓取https，例如https://github.com/ginuerzh/gost，通过gost生成了个SS，然后进行抓取报错。
![image](https://user-images.githubusercontent.com/52098233/235605786-cecb72f7-d75c-48b9-8bde-3dacb14de1be.png)

**Comment by Your7Maxx** [comment]
目标文件可能是使用单独的调试信息，而不是直接将符号嵌入到二进制文件中，所以是没办法hook的。可通过`readelf -Ws xxx`进行确认。
